# # config file version
apiVersion: 1

datasources:
 - name: graphite1
   type: graphite
   access: proxy
   orgId: 1
   url: http://carbonapi:80
   isDefault: True
   jsonData:
     graphiteVersion: "1.1"
